# Generated by Django 4.2.13 on 2024-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=20, unique=True)),
                ('time_date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
