# Generated by Django 4.2.13 on 2024-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='time_date_created',
            field=models.DateTimeField(),
        ),
    ]
